// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2S6Ce1hEeSND9e4WDBIWuz-6Rm-RZT8g',
    appId: '1:694185448383:web:eafec42385968364b0c70a',
    messagingSenderId: '694185448383',
    projectId: 'goal-tracker-app-f261e',
    authDomain: 'goal-tracker-app-f261e.firebaseapp.com',
    storageBucket: 'goal-tracker-app-f261e.firebasestorage.app',
    measurementId: 'G-ZVSD94BKXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqaadpsBIjVw6j0gvjSoIQYMi_NslGk5A',
    appId: '1:694185448383:android:8565f4f55fa0fa56b0c70a',
    messagingSenderId: '694185448383',
    projectId: 'goal-tracker-app-f261e',
    storageBucket: 'goal-tracker-app-f261e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDipz6F4X13pzMlFfv9rwIY4QiQTb91WAE',
    appId: '1:694185448383:ios:2de336f7a94aa63fb0c70a',
    messagingSenderId: '694185448383',
    projectId: 'goal-tracker-app-f261e',
    storageBucket: 'goal-tracker-app-f261e.firebasestorage.app',
    iosClientId: '694185448383-g59ugpb9kbcvonv8c1iofqmcp5atq593.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGoalTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDipz6F4X13pzMlFfv9rwIY4QiQTb91WAE',
    appId: '1:694185448383:ios:2210c55e85f85600b0c70a',
    messagingSenderId: '694185448383',
    projectId: 'goal-tracker-app-f261e',
    storageBucket: 'goal-tracker-app-f261e.firebasestorage.app',
    iosClientId: '694185448383-ua4ueg7l2tgescnstnigl3et30q6ofrf.apps.googleusercontent.com',
    iosBundleId: 'com.example.goalTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2S6Ce1hEeSND9e4WDBIWuz-6Rm-RZT8g',
    appId: '1:694185448383:web:ee44a0b27fdadf1db0c70a',
    messagingSenderId: '694185448383',
    projectId: 'goal-tracker-app-f261e',
    authDomain: 'goal-tracker-app-f261e.firebaseapp.com',
    storageBucket: 'goal-tracker-app-f261e.firebasestorage.app',
    measurementId: 'G-ZPTRMEDLR6',
  );
}
